Repository knative-sandbox/eventing-prometheus, pull requests merged in 2020-10, with the labels that each got.

#7 use utils in knative/pkg
  pkg/reconciler/prometheussource.go
  pkg/reconciler/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/S

#9 leverage new test-infra go_update_deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#10 Removed deprecated test images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#12 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#14 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#15 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#17 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S
