Repository knative-sandbox/eventing-prometheus, pull requests merged in 2020-12, with the labels that each got.

#34 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#35 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#37 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#39 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#38 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S
