Repository knative-sandbox/eventing-prometheus, pull requests merged in 2021-02, with the labels that each got.

#56 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#57 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#58 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#60 Remove @Harwayne from OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#61 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#63 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#64 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#65 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#67 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#66 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#68 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#69 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#70 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#71 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#73 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#72 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
