Repository knative-sandbox/eventing-prometheus, pull requests merged in 2021-04, with the labels that each got.

#90 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#92 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#94 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#95 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#97 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#98 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
