Repository knative-sandbox/eventing-prometheus, pull requests merged in 2021-08, with the labels that each got.

#134 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#132 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#136 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#139 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#141 Use `controller.Impl` tracker and cleanups
  pkg/reconciler/controller.go
Labels: cla: yes, approved, kind/cleanup, lgtm, size/XS

#143 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M
