Repository knative-sandbox/eventing-prometheus, pull requests merged in 2021-12, with the labels that each got.

#167 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#168 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/M

#169 Using v1 apis for CRD/Webhook
  config/300-prometheussource.yaml
  config/500-webhook-config.yaml
Labels: approved, size/L, lgtm

#171 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#170 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#172 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#174 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S
